language: swift

os:
  - osx

matrix:
  include:
    - osx_image: xcode10.3
      env: IPHONE_SIMULATOR_SDK='iphonesimulator12.4' OS_VERSION='12.4' IPHONE_NAME='iPhone Xs'
    - osx_image: xcode11.6
      env: IPHONE_SIMULATOR_SDK='iphonesimulator13.6' OS_VERSION='13.6' IPHONE_NAME='iPhone 11 Pro'
      script:
        # Ensure SPM builds
        - set -o pipefail && xcodebuild -workspace package.xcworkspace -scheme TABTestKit -sdk $IPHONE_SIMULATOR_SDK | xcpretty


addons:
  homebrew:
    brewfile: true
    update: false

script:
  # Ensure Carthage builds
  - carthage build --archive
  # Ensure Cocoapods builds
  - pod lib lint
  # Ensure tests pass
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit-Example -sdk $IPHONE_SIMULATOR_SDK -destination "OS=$OS_VERSION,name=$IPHONE_NAME" | xcpretty
