# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macOS-latest

    steps:
      - name: Set Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.6.app
      - name: Run tests
        run: xcodebuild build-for-testing -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6'
      - name: Test iPhone 11
        run: xcodebuild test-without-building -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1'
