
name: Manual workflow

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests on Xcode 11
        run: ./.github/workflows/run_tests.yml
